name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }} .

    - name: Tag the Docker image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_URI }}:latest

    - name: Push the Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_URI }}:latest
