name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to AWS ECR
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build the Docker image
      run: |
        cd Application-Code/backend
        docker build -t ${{ secrets.ECR_REPOSITORY }} .

    - name: Tag the Docker image
      run: |
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_URI }}:latest
   

    - name: Push the Docker image to ECR
      run: |
        set -e
        docker push ${{ secrets.ECR_URI }}:latest
