name: frontend CICD Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Use GitHub's hosted runners

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ./Kubernetes-Manifests-file/Frontend/deployment.yaml
          ./Kubernetes-Manifests-file/Frontend/service.yaml
        namespace: three-tier  # Specify your namespace, or remove if default
        
    - name: Check rollout status
      run: |
        kubectl rollout status deployment/frontend -n three-tier  # Check if the deployment was successful
