name: Terraform

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify your Terraform version
          working-directory: ./path/to/your/terraform/config  # Change this to your path

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Change this to your path

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform  # Change this to your path

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform  # Change this to your path

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform  # Change this to your path
